// FOOTDRAFT — season-league engine: double round-robin fixtures + the standings table.
//
// Pure + deterministic. A private league of up to 20 managers plays a double round-robin: every manager faces
// every other home AND away. For 20 teams that is exactly 38 matchdays — the literal "38-0". Going 38-0
// (winning all 38) is the dream. Fixtures are generated by the circle method; the table is the usual W/D/L,
// GD, points (win = 3, draw = 1). Match outcomes themselves come from MatchSim (your XI vs the opponent's
// locked drafted-XI snapshot), resolved elsewhere; this file only schedules and tallies.

using System.Collections.Generic;
using Metaplay.Core.Model;

namespace Game.Logic
{
    /// <summary> One scheduled fixture: team indices into the league's member list (0-based). </summary>
    [MetaSerializable]
    public class LeagueFixture
    {
        [MetaMember(1)] public int HomeIndex { get; set; }
        [MetaMember(2)] public int AwayIndex { get; set; }

        public LeagueFixture() { }
        public LeagueFixture(int homeIndex, int awayIndex)
        {
            HomeIndex = homeIndex;
            AwayIndex = awayIndex;
        }
    }

    /// <summary> A played fixture's scoreline + named goal details (input to the table + the results history). </summary>
    [MetaSerializable]
    public class LeagueResult
    {
        [MetaMember(1)] public int HomeIndex { get; set; }
        [MetaMember(2)] public int AwayIndex { get; set; }
        [MetaMember(3)] public int HomeGoals { get; set; }
        [MetaMember(4)] public int AwayGoals { get; set; }
        /// <summary> Timed goals with named scorer/assister (the "see who scored" detail). May be shorter than the scoreline on a goal-bonus matchday. </summary>
        [MetaMember(5)] public List<MatchGoalDetail> Goals { get; set; } = new List<MatchGoalDetail>();

        public LeagueResult() { }
        public LeagueResult(int homeIndex, int awayIndex, int homeGoals, int awayGoals)
        {
            HomeIndex = homeIndex;
            AwayIndex = awayIndex;
            HomeGoals = homeGoals;
            AwayGoals = awayGoals;
        }
    }

    /// <summary> One row of the standings table for a single team. </summary>
    [MetaSerializable]
    public class LeagueRow
    {
        [MetaMember(1)] public int TeamIndex    { get; set; }
        [MetaMember(2)] public int Played       { get; set; }
        [MetaMember(3)] public int Won          { get; set; }
        [MetaMember(4)] public int Drawn        { get; set; }
        [MetaMember(5)] public int Lost         { get; set; }
        [MetaMember(6)] public int GoalsFor     { get; set; }
        [MetaMember(7)] public int GoalsAgainst { get; set; }

        public LeagueRow() { }
        public LeagueRow(int teamIndex) { TeamIndex = teamIndex; }

        public int GoalDiff => GoalsFor - GoalsAgainst;
        public int Points   => Won * LeagueEngine.WinPoints + Drawn * LeagueEngine.DrawPoints;
    }

    public static class LeagueEngine
    {
        public const int WinPoints  = 3;
        public const int DrawPoints = 1;

        /// <summary>
        /// Builds a full double round-robin schedule for <paramref name="teamCount"/> teams (2..20): every team
        /// faces every other home and away. Returns matchdays, each a list of fixtures. For an even count there
        /// are 2·(teamCount-1) matchdays with teamCount/2 fixtures each; an odd count uses a bye (one team rests
        /// per matchday). The second leg mirrors the first with home/away swapped, so each pair meets once at each
        /// team's "home".
        /// </summary>
        public static List<List<LeagueFixture>> GenerateDoubleRoundRobin(int teamCount)
        {
            List<List<LeagueFixture>> schedule = new List<List<LeagueFixture>>();
            if (teamCount < 2)
                return schedule;

            bool odd   = (teamCount % 2) != 0;
            int  n     = odd ? teamCount + 1 : teamCount; // pad with a dummy "bye" team when odd
            int  dummy = n - 1;                            // only meaningful when odd
            int  rounds = n - 1;

            int[] arr = new int[n];
            for (int i = 0; i < n; i++)
                arr[i] = i;

            List<List<LeagueFixture>> firstLeg = new List<List<LeagueFixture>>();
            for (int r = 0; r < rounds; r++)
            {
                List<LeagueFixture> matchday = new List<LeagueFixture>();
                for (int i = 0; i < n / 2; i++)
                {
                    int t1 = arr[i];
                    int t2 = arr[n - 1 - i];
                    if (odd && (t1 == dummy || t2 == dummy))
                        continue; // the team paired with the dummy has a bye this matchday

                    // Alternate which side is home across rounds/slots so home games spread out.
                    bool t1Home = ((r + i) % 2) == 0;
                    matchday.Add(t1Home ? new LeagueFixture(t1, t2) : new LeagueFixture(t2, t1));
                }
                firstLeg.Add(matchday);

                // Circle method: fix arr[0], rotate the rest one step.
                int last = arr[n - 1];
                for (int k = n - 1; k > 1; k--)
                    arr[k] = arr[k - 1];
                arr[1] = last;
            }

            schedule.AddRange(firstLeg);

            // Second leg: the exact mirror of the first, home/away reversed.
            foreach (List<LeagueFixture> matchday in firstLeg)
            {
                List<LeagueFixture> mirrored = new List<LeagueFixture>(matchday.Count);
                foreach (LeagueFixture f in matchday)
                    mirrored.Add(new LeagueFixture(f.AwayIndex, f.HomeIndex));
                schedule.Add(mirrored);
            }

            return schedule;
        }

        /// <summary> Builds the standings table from results, sorted by points, then goal difference, then goals for. </summary>
        public static List<LeagueRow> ComputeTable(int teamCount, IEnumerable<LeagueResult> results)
        {
            List<LeagueRow> rows = new List<LeagueRow>(teamCount);
            for (int i = 0; i < teamCount; i++)
                rows.Add(new LeagueRow(i));

            foreach (LeagueResult res in results)
            {
                if (res.HomeIndex < 0 || res.HomeIndex >= teamCount || res.AwayIndex < 0 || res.AwayIndex >= teamCount)
                    continue;

                LeagueRow home = rows[res.HomeIndex];
                LeagueRow away = rows[res.AwayIndex];

                home.Played++; away.Played++;
                home.GoalsFor += res.HomeGoals; home.GoalsAgainst += res.AwayGoals;
                away.GoalsFor += res.AwayGoals; away.GoalsAgainst += res.HomeGoals;

                if (res.HomeGoals > res.AwayGoals)      { home.Won++;  away.Lost++; }
                else if (res.HomeGoals < res.AwayGoals) { away.Won++;  home.Lost++; }
                else                                    { home.Drawn++; away.Drawn++; }
            }

            rows.Sort((a, b) =>
            {
                if (a.Points    != b.Points)    return b.Points.CompareTo(a.Points);
                if (a.GoalDiff  != b.GoalDiff)  return b.GoalDiff.CompareTo(a.GoalDiff);
                if (a.GoalsFor  != b.GoalsFor)  return b.GoalsFor.CompareTo(a.GoalsFor);
                return a.TeamIndex.CompareTo(b.TeamIndex);
            });
            return rows;
        }

        /// <summary> Matchdays in a double round-robin for the given team count (2·(n-1) for even n). </summary>
        public static int MatchdayCount(int teamCount)
        {
            if (teamCount < 2) return 0;
            int n = (teamCount % 2) != 0 ? teamCount + 1 : teamCount;
            return 2 * (n - 1);
        }
    }
}
